sonar.projectKey=meshora-labs_mesh
sonar.projectName=Mesh
sonar.organization=meshora-labs
sonar.projectVersion=0.1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/.vscode/**, **/.idea/**, **/coverage/**, **/public/**